version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'elhura_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'elhura'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'elhura'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./mysql/elhura-db:/var/lib/mysql
      - ./elhura.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  elhura_mysql_volume:
